# Account Microservice

server:
  port: ${ACCOUNT_PORT}

spring:
  application:
    name: "account"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    username: "${MYSQLDB}"
    password: "${MYSQLDB_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DATABASE_NAME}:${DBPORT}/${DBNAME}"
    initialization-mode: always

app:
  security:
    secret-key: ${SECRET_KEY}
    jwt:
      secret-key: ${JWT_SECRET_KEY}
